env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - plugin:prettier/recommended
rules:
  import/prefer-default-export: off
  import/extensions: off
parserOptions:
  ecmaVersion: 2022