const MSG_GAME_START = '숫자 야구 게임을 시작합니다.';
const MSG_GAME_OVER = '3개의 숫자를 모두 맞히셨습니다! 게임 종료';
const MSG_GAME_RESTART = '게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요.';
const MSG_ENTER_THE_NUMBER = '숫자를 입력해주세요 : ';
const ERROR_MSG_INPUT_NUMBER = '[ERROR] 숫자가 잘못된 형식입니다.';
const VALUE_RESTART_GAME = '1';
const VALUE_END_GAME = '2';
const VALUE_MAX_GAME_INPUT_DIGIT = 3;
const RANDOM_NUMBER_RANGE_FROM = 1;
const RANDOM_NUMBER_RANGE_TO = 9;
const USER_INPUT_RANGE_FROM = '1';
const USER_INPUT_RANGE_TO = '9';

export {
  MSG_GAME_START,
  MSG_GAME_OVER,
  MSG_GAME_RESTART,
  MSG_ENTER_THE_NUMBER,
  ERROR_MSG_INPUT_NUMBER,
  VALUE_RESTART_GAME,
  VALUE_END_GAME,
  VALUE_MAX_GAME_INPUT_DIGIT,
  RANDOM_NUMBER_RANGE_FROM,
  RANDOM_NUMBER_RANGE_TO,
  USER_INPUT_RANGE_FROM,
  USER_INPUT_RANGE_TO,
};
